name: Docker Image CI

on:
  create:
    tags:
      - v*

jobs:

  push:
    runs-on: ubuntu-latest
    name: Push image to Docker Hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract tag name
        shell: bash
        run: echo "DOCKER_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest .
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{ env.DOCKER_TAG }}
          docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{ env.DOCKER_TAG }}
          docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:latest